name: Deploy Node.js Backend

on:
  push:
    branches:
      - main  # adjust if your main backend branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."                     # ✅ project root
          target: "/root/cyt_backend_api"  # ✅ full path to backend folder
          strip_components: 0             # ✅ do NOT strip anything

      - name: Install & restart backend on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "📂 Switching to project directory..."
            cd /root/cyt_backend_api || { echo "❌ Folder not found"; exit 1; }

            echo "📦 Installing production dependencies..."
            npm install --production || { echo "❌ npm install failed"; exit 1; }

            echo "♻️ Restarting backend..."
            pm2 delete cyt_backend || true
            pm2 start index.js --name cyt_backend
