name: Deploy Node.js Backend

on:
  push:
    branches:
      - main  # or your backend branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clean backend folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🧹 Cleaning old backend directory..."
            rm -rf ${{ secrets.VPS_BACKEND_PATH }}/*

      - name: Deploy backend to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: ${{ secrets.VPS_BACKEND_PATH }}
          strip_components: 1

      - name: Restart PM2 on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_BACKEND_PATH }} || exit 1
            npm install --production

            echo "♻️ Restarting backend..."
            pm2 delete cyt_backend || true
            pm2 start index.js --name cyt_backend



