name: Deploy Node.js Backend

on:
  push:
    branches:
      - main  # or your backend branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "cyt_backend_api/*"
          target: ${{ secrets.VPS_BACKEND_PATH }}
          strip_components: 1

      - name: Restart PM2 on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: ${{ secrets.VPS_DEPLOY_PATH }}
          script: |
            cd ${{ secrets.VPS_BACKEND_PATH }}
            npm install --production
            pm2 restart cyt-backend
